Rayt 52 skybox en .png
BLOOP-BLOOP-TEAM/raytracer pull request #51
Opened 2023-05-09 18:13 UTC by alexandrelagasse

2023-05-09 22:34 UTC, Nabzilooo approved these changes

2023-05-10 07:15 UTC, KitetsuK requested changes

2023-05-10 07:15 UTC, KitetsuK commented on src/Raytracer/Display/Calculator.hpp
> +#include "../../Plugins/SimpleSkybox/Skybox.hpp"
path en dur

2023-05-10 07:15 UTC, KitetsuK commented on src/Raytracer/Display/Image.hpp
> +#include "../../Plugins/SimpleSkybox/Skybox.hpp"
path en dur

2023-05-10 07:22 UTC, KitetsuK approved these changes

2023-05-10 07:24 UTC, merged